return{}
       -- -- lspconfig.texlab.setup{on_attach=require'completion'.on_attach}
       -- -- lspconfig.ltex.setup{on_attach=require'completion'.on_attach}
       -- -- lspconfig.ltex.setup{}
       -- -- How to ignore errors of italian words?
       -- -- lspconfig.ltex.setup{autostart=false,filetypes={"bib", "gitcommit", "markdown", "org", "plaintex", "rst", "rnoweb", "tex","vimwiki"}}
       -- -- Does it autocorrect?
       -- ['ltex'] = function()
       --   lspconfig.ltex.setup({
       --     autostart = false,
       --     filetypes = { 'bib', 'gitcommit', 'markdown', 'org', 'plaintex', 'rst', 'rnoweb', 'tex', --[['vimwiki',]] 'srt' },
       --     -- settings = { ltex = { language = "it" } },
       --     -- possible to have dynamic settings? wrap this in a function and use expr=true
       --     -- I guess you need autostart=false for this?
       --     -- https://valentjn.github.io/ltex/advanced-usage.html#magic-comments
       --     -- settings = { ltex = { language = vim.o.spelllang } },
       --     settings = { ltex = { language = 'it' } },
       --   })
       --   --  The config currently requires that you're working in a git repo.
       -- end
