return {}
-- return {
--   {
--     'simrat39/rust-tools.nvim',
--     dependencies = 'nvim-lspconfig',
--     event = { 'BufReadPost *.rs', 'BufNewFile *.rs' },
--     config = function()
--       local rt = require 'rust-tools'
--       rt.setup { ... }
--     end
--   }
-- }
