-- https://github.com/f-person/pubspec-assist-nvim?tab=readme-ov-file
-- flutter tools nvim
return {}
-- https://github.com/mfussenegger/nvim-dap/issues/1020
      -- -- Dart / Flutter
      -- dap.adapters.dart = {
      --   type = 'executable',
      --   command = vim.fn.stdpath('data')..'/mason/bin/dart-debug-adapter',
      --   args = {'dart'}
      -- }
      -- dap.adapters.flutter = {
      --   type = 'executable',
      --   command = vim.fn.stdpath('data')..'/mason/bin/dart-debug-adapter',
      --   args = {'flutter'}
      -- }
      -- dap.configurations.dart = {
      --   {
      --     type = "dart",
      --     request = "launch",
      --     name = "Launch dart",
      --     dartSdkPath = "/opt/flutter/bin/cache/dart-sdk/", -- ensure this is correct
      --     flutterSdkPath = "/opt/flutter",                  -- ensure this is correct
      --     program = "${workspaceFolder}/lib/main.dart",     -- ensure this is correct
      --     cwd = "${workspaceFolder}",
      --   },
      --   {
      --     type = "dart",
      --     request = "launch",
      --     name = "Launch flutter",
      --     dartSdkPath = "/opt/flutter/bin/cache/dart-sdk/", -- ensure this is correct
      --     flutterSdkPath = "/opt/flutter",                  -- ensure this is correct
      --     program = "${workspaceFolder}/lib/main.dart",     -- ensure this is correct
      --     cwd = "${workspaceFolder}",
      --   }
      -- }

-- {
--     'nvim-flutter/flutter-tools.nvim',
--     lazy = false,
--     dependencies = {
--         'nvim-lua/plenary.nvim',
--     },
--     config = true,
-- }
